# -*- coding: utf-8 -*-
"""scratchpad

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/empty.ipynb
"""

!pip install beautifulsoup4

import bs4 as bs
TH_FULL_WEEKDAYS = [
    "วันจันทร์",
    "วันอังคาร",
    "วันพุธ",
    "วันพฤหัสบดี",
    "วันศุกร์",
    "วันเสาร์",
    "วันอาทิตย์",
]
def readfile_as_text(filename):
    text=None
    with open(filename, 'r', encoding='utf-8') as file:
            text=file.read()
    return text
def Q1(filepath):
    text=readfile_as_text(filepath)
    soup = bs.BeautifulSoup(text, 'html.parser')
    holydays=[text.select('div')[0].text for text in soup.select('.bud-day')]
    counter_map = dict.fromkeys(TH_FULL_WEEKDAYS,0)
    holy_weekdays = [day.split()[0].replace('ที่','') for day in holydays]
    for day in holy_weekdays:
        counter_map[day] += 1
    return [counter_map[key] for key in TH_FULL_WEEKDAYS]
def Q2(filepath):
    text=readfile_as_text(filepath)
    soup = bs.BeautifulSoup(text, 'html.parser')
    date_string = soup.select('a[title="วันวิสาขบูชา"]')[0].parent.parent.select('div')[0].text
    return date_string

exec(input().strip())